import type { GameEvent } from '../types/events';

export const DYNAMIC_EVENTS: GameEvent[] = [
  {
    id: 'evt_flood_1',
    category: 'DISASTER',
    headlineHi: 'भारी मानसूनी बारिश से गंगा-कोसी कछार में भयंकर बाढ़ का संकट',
    headlineEn: 'Severe Flash Floods in River Basin Threatens Thousands',
    descriptionHi: 'लगातार 48 घंटे हुई मूसलाधार वर्षा से 12 जिलों में बाढ़ आ गई है। 50,000 से अधिक नागरिक विस्थापित हुए हैं। विपक्ष सहायता में देरी का आरोप लगा रहा है।',
    descriptionEn: 'Torrential rainfall over 48 hours has flooded low-lying districts, displacing over 50,000 families. Opposition claims administrative delay.',
    affectedRegion: 'Eastern Plains',
    isUrgent: true,
    timeLimitSeconds: 45,
    choices: [
      {
        id: 'c1',
        titleHi: 'आपातकालीन राहत पैकेज (₹50 लाख) व सेना/NDRF की तैनाती',
        titleEn: 'Immediate ₹50L Relief Package + Deploy NDRF & Helicopters',
        descHi: 'बिना विलंब राजकोष से सहायता राशि जारी करें और स्वयं ग्राउंड जीरो का हवाई व स्थलीय दौरा करें।',
        descEn: 'Disburse immediate funds, deploy rescue forces, and personally inspect ground zero.',
        cost: 50000,
        timeDays: 3,
        risk: 'LOW',
        expectedEffectHi: 'जनविश्वास में भारी वृद्धि (+12%), राहत कार्य में तेजी',
        expectedEffectEn: 'Big surge in Public Trust (+12%), swift relief operations',
        consequenceHi: 'आपकी तत्परता और संवेदनशीलता की देश भर में सराहना हुई। पीड़ितों को तत्काल राशन और दवाएं मिलीं।',
        consequenceEn: 'Your swift compassion won nationwide admiration. Displaced citizens received quick food and medical aid.',
        trustChange: 12,
        popularityChange: 8,
        supportChanges: { rural: 10, farmers: 12 }
      },
      {
        id: 'c2',
        titleHi: 'स्थानीय प्रशासन व जिलाधिकारियों को स्थिति संभालने के निर्देश दें',
        titleEn: 'Delegate Response to Local District Magistrates',
        descHi: 'बजट सीमित रखें और राज्य आपदा राहत कोष से सामान्य गति से काम करने को कहें।',
        descEn: 'Conserve party/state reserves and instruct regular bureaucratic protocols.',
        cost: 10000,
        timeDays: 1,
        risk: 'MEDIUM',
        expectedEffectHi: 'धन की बचत, परंतु विपक्ष को आलोचना का अवसर',
        expectedEffectEn: 'Saves funds, but media and opposition will criticize delay',
        consequenceHi: 'राहत कार्य में थोड़ी देरी हुई। स्थानीय अखबारों में प्रशासनिक सुस्ती की खबरें छपीं।',
        consequenceEn: 'Relief distribution lagged slightly. Local editorials criticized bureaucratic delays.',
        trustChange: -4,
        popularityChange: -2,
        supportChanges: { rural: -5 }
      },
      {
        id: 'c3',
        titleHi: 'पार्टी कार्यकर्ताओं को नाव और सूखा राशन लेकर सेवा में झोंकें',
        titleEn: 'Mobilize Party Cadres with Food & Boats for Ground Seva',
        descHi: 'सरकारी प्रक्रिया से इतर पार्टी के 500 स्वयंसेवकों को सीधे बचाव में उतारें।',
        descEn: 'Deploy 500 active party volunteers directly with dry rations and rescue boats.',
        cost: 25000,
        timeDays: 2,
        risk: 'LOW',
        expectedEffectHi: 'पार्टी की जमीन पर पकड़ मजबूत (+15% कार्यकर्ता मनोबल)',
        expectedEffectEn: 'Strong cadre mobilization & emotional grassroots connect',
        consequenceHi: 'पार्टी के सेवा भाव ने जनता का दिल जीत लिया। युवाओं में पार्टी से जुड़ने की होड़ लग गई।',
        consequenceEn: 'Grassroots service deeply moved local voters. Party membership spiked among youth.',
        trustChange: 10,
        popularityChange: 9,
        supportChanges: { youth: 12, rural: 8 }
      }
    ]
  },
  {
    id: 'evt_media_trial_1',
    category: 'MEDIA_TRIAL',
    headlineHi: 'प्राइम टाइम डिबेट: विपक्षी दल ने घोषणापत्र के वादों को बताया "अव्यावहारिक"',
    headlineEn: 'Prime Time Debate: Opposition Brands Your Manifesto "Unrealistic"',
    descriptionHi: 'एक बड़े राष्ट्रीय समाचार चैनल पर विपक्ष के प्रवक्ता ने आपके रोजगार और स्वास्थ्य मॉडल पर सवाल उठाते हुए इसे "काल्पनिक ख्याली पुलाव" करार दिया है।',
    descriptionEn: 'On a prime-time news broadcast, the opposition spokesperson questioned the financial viability of your healthcare and employment pledges.',
    isUrgent: false,
    choices: [
      {
        id: 'c1',
        titleHi: 'लाइव टीवी डिबेट में स्वयं उपस्थित होकर डेटा व तथ्यों सहित चुनौती दें',
        titleEn: 'Personally Appear on Prime-Time Debate with Data & Facts',
        descHi: 'एंकर और विपक्षी प्रवक्ता के हर प्रश्न का आंकड़ों और बजटीय गणना के साथ तार्किक उत्तर दें।',
        descEn: 'Confront the anchor and opposition head-on with detailed economic modeling.',
        cost: 15000,
        timeDays: 1,
        risk: 'MEDIUM',
        expectedEffectHi: 'सफल रहे तो छवि में भारी उछाल (+10 संचार), असफल रहे तो विवाद',
        expectedEffectEn: 'High reward if communicative, risk of intense cross-questioning',
        consequenceHi: 'आपके शांत और तथ्यपरक उत्तरों ने विपक्षी नेता को निरुत्तर कर दिया। सोशल मीडिया पर आपका क्लिप वायरल हो गया!',
        consequenceEn: 'Your composed and data-backed rebuttal silenced critics. Video clips trended #1 across platforms!',
        trustChange: 8,
        popularityChange: 11,
        supportChanges: { youth: 10, urban: 8 }
      },
      {
        id: 'c2',
        titleHi: 'पार्टी के मुख्य अर्थशास्त्री व मुख्य प्रवक्ता को आधिकारिक प्रेस कॉन्फ्रेंस में भेजें',
        titleEn: 'Field Party Chief Economist at Press Club Briefing',
        descHi: 'संयमित तरीके से लिखित श्वेतपत्र और प्रेस रिलीज जारी कर स्थिति स्पष्ट करें।',
        descEn: 'Release an official white paper outlining exact fiscal allocations.',
        cost: 8000,
        timeDays: 1,
        risk: 'LOW',
        expectedEffectHi: 'सुरक्षित दांव, गंभीर बौद्धिक वर्ग का समर्थन',
        expectedEffectEn: 'Safe measured response, wins praise from intellectuals and experts',
        consequenceHi: 'प्रेस कॉन्फ्रेंस से नीति विश्लेषक संतुष्ट हुए। विवाद 24 घंटे में शांत हो गया।',
        consequenceEn: 'Policy analysts approved the nuanced white paper. Controversy petered out cleanly.',
        trustChange: 5,
        popularityChange: 4,
        supportChanges: { business: 6, urban: 5 }
      },
      {
        id: 'c3',
        titleHi: 'इस बहस को राजनीतिक दुर्भावना बताकर सीधे जनता के बीच नुक्कड़ सभा करें',
        titleEn: 'Bypass TV Studios: Hold Direct Jan Chaupal with Citizens',
        descHi: 'टीवी बहसों की उपेक्षा कर सीधे मतदाताओं के बीच जाकर अपनी बात रखें।',
        descEn: 'Ignore studio pundits and take the manifesto pitch directly to ordinary citizens.',
        cost: 12000,
        timeDays: 2,
        risk: 'LOW',
        expectedEffectHi: 'आम जनता से सीधा जुड़ाव (+8 ग्रामीण समर्थन)',
        expectedEffectEn: 'Direct grassroots connect, bypassing elite studio noise',
        consequenceHi: 'जनता ने कहा- "हमारा नेता स्टूडियो में नहीं, सड़कों पर हमारे साथ खड़ा है।"',
        consequenceEn: 'Citizens appreciated direct engagement: "Our leader walks with us on the streets!"',
        trustChange: 7,
        popularityChange: 6,
        supportChanges: { rural: 9, workers: 8 }
      }
    ]
  },
  {
    id: 'evt_agri_1',
    category: 'ECONOMIC_SHOCK',
    headlineHi: 'बेमौसम ओलावृष्टि से फसलों को भारी नुकसान: किसानों की महापंचायत',
    headlineEn: 'Unseasonal Hailstorm Ravages Standing Crops: Farmers Gather',
    descriptionHi: 'कटाई से ठीक पहले ओलावृष्टि ने गेहूं और दलहन की फसलों को 40% तक बर्बाद कर दिया है। किसान मुआवजे और ऋण माफी की मांग को लेकर राजमार्ग पर एकत्रित हैं।',
    descriptionEn: 'Hailstorms damaged standing wheat and pulses right before harvest. Farmers have gathered seeking immediate compensation and loan restructuring.',
    isUrgent: true,
    timeLimitSeconds: 50,
    choices: [
      {
        id: 'c1',
        titleHi: 'तुरंत ₹25,000 प्रति एकड़ सीधा बैंक खाता अंतरण (DBT) घोषित करें',
        titleEn: 'Announce Direct Bank Transfer (₹25,000/acre) to Affected Farmers',
        descHi: 'किसान कल्याण कोष से सीधा मुआवजा जारी करें और मंडी उपकर 6 माह के लिए माफ करें।',
        descEn: 'Fast-track direct cash transfers and waive APMC market fees for six months.',
        cost: 60000,
        timeDays: 2,
        risk: 'LOW',
        expectedEffectHi: 'किसानों का पूर्ण समर्थन (+18%), विपक्ष का आंदोलन समाप्त',
        expectedEffectEn: 'Massive surge in Farmer support (+18%), protest ends peacefully',
        consequenceHi: 'किसानों ने आपकी जय-जयकार की। महापंचायत उत्सव में बदल गई और आंदोलन समाप्त हुआ।',
        consequenceEn: 'Farmers celebrated the relief package. The protest dissolved into a celebratory rally.',
        trustChange: 14,
        popularityChange: 12,
        supportChanges: { farmers: 20, rural: 15 }
      },
      {
        id: 'c2',
        titleHi: 'फसल बीमा कंपनियों से 7 दिन के भीतर सर्वे कर क्लेम देने का सख्त आदेश',
        titleEn: 'Strict Mandate to Crop Insurance Companies for 7-Day Settlement',
        descHi: 'सरकारी खजाने पर बोझ डाले बिना बीमा कंपनियों पर दबाव बनाएं।',
        descEn: 'Order insurance firms to disburse claims within 7 days under penalty threat.',
        cost: 5000,
        timeDays: 2,
        risk: 'MEDIUM',
        expectedEffectHi: 'कम खर्च, लेकिन यदि कंपनियों ने आनाकानी की तो नाराजगी का जोखिम',
        expectedEffectEn: 'Fiscal savings, but delays could risk farmer dissatisfaction',
        consequenceHi: 'लगभग 60% किसानों को क्लेम मिला, परंतु कुछ क्षेत्रों में कागजी अड़चनों से असंतोष रहा।',
        consequenceEn: 'Around 60% farmers got claims, but paperwork hurdles left some pockets disgruntled.',
        trustChange: 3,
        popularityChange: 2,
        supportChanges: { farmers: 4 }
      }
    ]
  },
  {
    id: 'evt_tech_1',
    category: 'OPPORTUNITY',
    headlineHi: 'वैश्विक टेक कंपनी ने आपके राज्य में ₹20,000 करोड़ का सेमीकंडक्टर प्लांट लगाने का प्रस्ताव रखा',
    headlineEn: 'Global Tech Giant Proposes ₹20,000 Cr Semiconductor Mega-Fab',
    descriptionHi: 'यदि मंजूरी मिलती है तो 35,000 उच्च-वेतन युक्त नौकरियां सृजित होंगी, परंतु इसके लिए पर्यावरण नियमों में कुछ छूट और सस्ती बिजली की मांग की गई है।',
    descriptionEn: 'The project could create 35,000 high-tech jobs, but requests green clearances acceleration and subsidized industrial power.',
    isUrgent: false,
    choices: [
      {
        id: 'c1',
        titleHi: 'प्रोजेक्ट को फास्ट-ट्रैक सिंगल विंडो मंजूरी दें व "ग्रीन टेक पार्क" बनाएं',
        titleEn: 'Fast-Track Single-Window Clearance with Solar Power Mandate',
        descHi: 'निवेश आकर्षित करें और शर्त रखें कि 70% स्थानीय युवाओं को प्राथमिकता मिले।',
        descEn: 'Grant accelerated approval while mandating 70% local youth employment.',
        cost: 20000,
        timeDays: 3,
        risk: 'LOW',
        expectedEffectHi: 'युवा वर्ग व व्यापारियों में प्रचंड उत्साह (+15%), रोजगार वृद्धि',
        expectedEffectEn: 'Massive excitement among Youth & Business (+15%), boost to GDP',
        consequenceHi: 'राज्य को "सिलिकॉन हब" घोषित किया गया! युवाओं ने सोशल मीडिया पर आपके दूरदर्शी विजन का स्वागत किया।',
        consequenceEn: 'State hailed as next semiconductor hub! Thousands of tech students celebrated your visionary leap.',
        trustChange: 11,
        popularityChange: 14,
        supportChanges: { youth: 18, business: 16, urban: 12 }
      },
      {
        id: 'c2',
        titleHi: 'सख्त पर्यावरणीय समीक्षा के बाद ही सशर्त अनुमति दें',
        titleEn: 'Subject to Comprehensive Environmental & Water Impact Audit',
        descHi: 'भूजल और स्थानीय कृषि भूमि की रक्षा हेतु विशेषज्ञ समिति गठित करें।',
        descEn: 'Set up an independent environmental panel to protect local groundwater.',
        cost: 10000,
        timeDays: 4,
        risk: 'MEDIUM',
        expectedEffectHi: 'पर्यावरणविदों की प्रशंसा, पर कंपनी द्वारा अन्य राज्य जाने का जोखिम',
        expectedEffectEn: 'Praised by environmentalists, slight delay in investment',
        consequenceHi: 'कंपनी ने पर्यावरण अनुकूल डिजाइन पर सहमति जताई। टिकाऊ विकास का बेहतरीन मॉडल स्थापित हुआ।',
        consequenceEn: 'The firm accepted stringent eco-standards, creating an admired sustainable growth model.',
        trustChange: 8,
        popularityChange: 6,
        supportChanges: { rural: 6, urban: 5 }
      }
    ]
  }
];
