import type { Constituency, OppositionParty, Achievement } from '../types/game';
import type { TrainingProgram } from '../types/quiz';
import type { Minister } from '../types/parliament';

export const INDIA_STATES = [
  'Uttar Pradesh',
  'Maharashtra',
  'Bihar',
  'West Bengal',
  'Madhya Pradesh',
  'Tamil Nadu',
  'Rajasthan',
  'Karnataka',
  'Gujarat',
  'Andhra Pradesh',
  'Odisha',
  'Telangana',
  'Kerala',
  'Jharkhand',
  'Assam',
  'Punjab',
  'Chhattisgarh',
  'Haryana',
  'Delhi',
  'Jammu & Kashmir',
  'Uttarakhand',
  'Himachal Pradesh',
  'Tripura',
  'Meghalaya',
  'Manipur',
  'Nagaland',
  'Goa',
  'Arunachal Pradesh',
  'Mizoram',
  'Sikkim'
];

export const INITIAL_CONSTITUENCIES: Constituency[] = [
  {
    id: 'const_1',
    name: 'काशीपुर (Kashipur)',
    state: 'Uttar Pradesh',
    district: 'Varanasi Zone',
    voterCount: 1850000,
    urbanPercent: 65,
    ruralPercent: 35,
    playerSupport: 32,
    oppositionSupport: { opp_1: 38, opp_2: 24, opp_3: 6 },
    keyIssue: 'सड़कें, स्वच्छता व गंगा घाट विकास',
    keyIssueEn: 'Infrastructure, sanitation & tourism',
    isPlayerHome: true,
    isUnlocked: true,
  },
  {
    id: 'const_2',
    name: 'कौशाम्बी नगर (Kaushambi Nagar)',
    state: 'Uttar Pradesh',
    district: 'Prayagraj Zone',
    voterCount: 1720000,
    urbanPercent: 40,
    ruralPercent: 60,
    playerSupport: 25,
    oppositionSupport: { opp_1: 42, opp_2: 26, opp_3: 7 },
    keyIssue: 'कृषि ऋण, उर्वरक व ग्रामीण अस्पताल',
    keyIssueEn: 'Farm credit, fertilizers & rural health',
    isPlayerHome: false,
    isUnlocked: true,
  },
  {
    id: 'const_3',
    name: 'अवध पश्चिम (Awadh West)',
    state: 'Uttar Pradesh',
    district: 'Lucknow Central',
    voterCount: 1950000,
    urbanPercent: 85,
    ruralPercent: 15,
    playerSupport: 28,
    oppositionSupport: { opp_1: 45, opp_2: 20, opp_3: 7 },
    keyIssue: 'युवा रोजगार, आईटी पार्क व सार्वजनिक परिवहन',
    keyIssueEn: 'Youth jobs, IT parks & public transit',
    isPlayerHome: false,
    isUnlocked: false,
  },
  {
    id: 'const_4',
    name: 'मगध मध्य (Magadh Central)',
    state: 'Bihar',
    district: 'Patna Region',
    voterCount: 2100000,
    urbanPercent: 55,
    ruralPercent: 45,
    playerSupport: 22,
    oppositionSupport: { opp_1: 35, opp_2: 38, opp_3: 5 },
    keyIssue: 'बाढ़ नियंत्रण व शिक्षा संस्थान',
    keyIssueEn: 'Flood management & higher education',
    isPlayerHome: false,
    isUnlocked: false,
  },
  {
    id: 'const_5',
    name: 'कोंकण सागर (Konkan Sagar)',
    state: 'Maharashtra',
    district: 'Mumbai Suburb',
    voterCount: 2200000,
    urbanPercent: 95,
    ruralPercent: 5,
    playerSupport: 26,
    oppositionSupport: { opp_1: 40, opp_2: 28, opp_3: 6 },
    keyIssue: 'लोकल ट्रेन भीड़ नियंत्रण व जल निकासी',
    keyIssueEn: 'Local train infrastructure & drainage',
    isPlayerHome: false,
    isUnlocked: false,
  },
  {
    id: 'const_6',
    name: 'मालवा उत्तर (Malwa North)',
    state: 'Madhya Pradesh',
    district: 'Indore Hub',
    voterCount: 1650000,
    urbanPercent: 70,
    ruralPercent: 30,
    playerSupport: 29,
    oppositionSupport: { opp_1: 46, opp_2: 20, opp_3: 5 },
    keyIssue: 'स्वच्छता निरंतरता व लघु उद्योग संवर्धन',
    keyIssueEn: 'Sustained cleanliness & MSME incentives',
    isPlayerHome: false,
    isUnlocked: false,
  }
];

export const INITIAL_OPPOSITION_PARTIES: OppositionParty[] = [
  {
    id: 'opp_1',
    name: 'प्रगतिशील लोकतांत्रिक मोर्चा',
    shortName: 'PLM',
    leader: 'राघवेंद्र शर्मा',
    symbol: 'Sun',
    color: '#E11D48',
    popularity: 42,
    funds: 2500000,
    seats: 180,
    stance: 'AGGRESSIVE',
  },
  {
    id: 'opp_2',
    name: 'जन कल्याण परिषद',
    shortName: 'JKP',
    leader: 'सुमित्रा देवी',
    symbol: 'Scale',
    color: '#2563EB',
    popularity: 35,
    funds: 1800000,
    seats: 135,
    stance: 'CENTRIST',
  },
  {
    id: 'opp_3',
    name: 'राष्ट्रीय स्वराज्य दल',
    shortName: 'RSD',
    leader: 'दिग्विजय सिंह',
    symbol: 'Shield',
    color: '#0D9488',
    popularity: 18,
    funds: 950000,
    seats: 60,
    stance: 'POPULIST',
  }
];

export const INITIAL_CABINET: Minister[] = [
  {
    id: 'min_1',
    name: 'डॉ. आनंद वर्धन',
    ministryId: 'FINANCE',
    ministryTitleHi: 'वित्त व कॉर्पोरेट कार्य मंत्रालय',
    ministryTitleEn: 'Ministry of Finance & Corporate Affairs',
    loyalty: 88,
    competence: 92,
    integrity: 90,
    image: 'banknote',
  },
  {
    id: 'min_2',
    name: 'सरदार बलविंदर सिंह',
    ministryId: 'HOME_AFFAIRS',
    ministryTitleHi: 'गृह व आंतरिक सुरक्षा मंत्रालय',
    ministryTitleEn: 'Ministry of Home Affairs',
    loyalty: 94,
    competence: 86,
    integrity: 88,
    image: 'shield',
  },
  {
    id: 'min_3',
    name: 'प्रो. मीनाक्षी नायर',
    ministryId: 'EDUCATION',
    ministryTitleHi: 'शिक्षा व कौशल विकास मंत्रालय',
    ministryTitleEn: 'Ministry of Education & Skill Development',
    loyalty: 85,
    competence: 94,
    integrity: 95,
    image: 'graduation-cap',
  },
  {
    id: 'min_4',
    name: 'डॉ. राजेंद्र कुलकर्णी',
    ministryId: 'HEALTHCARE',
    ministryTitleHi: 'स्वास्थ्य व परिवार कल्याण मंत्रालय',
    ministryTitleEn: 'Ministry of Health & Family Welfare',
    loyalty: 82,
    competence: 91,
    integrity: 93,
    image: 'heart-pulse',
  },
  {
    id: 'min_5',
    name: 'चौधरी चरणदास पटेल',
    ministryId: 'AGRICULTURE',
    ministryTitleHi: 'कृषि व कृषक कल्याण मंत्रालय',
    ministryTitleEn: 'Ministry of Agriculture & Farmers Welfare',
    loyalty: 90,
    competence: 89,
    integrity: 87,
    image: 'wheat',
  },
  {
    id: 'min_6',
    name: 'इंजी. विक्रम राठौड़',
    ministryId: 'INFRASTRUCTURE',
    ministryTitleHi: 'सड़क परिवहन व राजमार्ग मंत्रालय',
    ministryTitleEn: 'Ministry of Road Transport & Highways',
    loyalty: 86,
    competence: 90,
    integrity: 84,
    image: 'truck',
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    titleHi: 'राजनीति का पहला कदम',
    titleEn: 'First Step in Politics',
    descHi: 'आम नागरिक से निकलकर अपनी राजनीतिक पार्टी की स्थापना की।',
    descEn: 'Emerged from civil life to successfully register a political party.',
    icon: 'flag',
    unlocked: true,
  },
  {
    id: 'ach_2',
    titleHi: 'प्रथम चुनावी समर',
    titleEn: 'First Campaign Trail',
    descHi: 'अपने पहले विधानसभा क्षेत्र में 10 से अधिक जनसभाएं कीं।',
    descEn: 'Conducted over 10 campaign outreach actions in your constituency.',
    icon: 'megaphone',
    unlocked: false,
  },
  {
    id: 'ach_3',
    titleHi: 'ऐतिहासिक जनादेश',
    titleEn: 'First Electoral Victory',
    descHi: 'अपने गृह क्षेत्र से चुनाव जीतकर जनप्रतिनिधि बने।',
    descEn: 'Won your first election and entered the legislative hall.',
    icon: 'trophy',
    unlocked: false,
  },
  {
    id: 'ach_4',
    titleHi: 'संसद का सफर',
    titleEn: 'Member of Parliament',
    descHi: 'लोकसभा चुनाव जीतकर देश की संसद के सदस्य बने।',
    descEn: 'Elected as a Member of Parliament in Lok Sabha.',
    icon: 'landmark',
    unlocked: false,
  },
  {
    id: 'ach_5',
    titleHi: 'देश का प्रधान सेवक',
    titleEn: 'Prime Minister of Bharat',
    descHi: 'लोकसभा में बहुमत हासिल कर भारत के प्रधानमंत्री पद की शपथ ली।',
    descEn: 'Formed government and assumed the office of Prime Minister.',
    icon: 'crown',
    unlocked: false,
  },
  {
    id: 'ach_6',
    titleHi: 'संकट मोचक',
    titleEn: 'Crisis Navigator',
    descHi: 'देश में आए भीषण प्राकृतिक या आर्थिक संकट का सफलतापूर्वक समाधान किया।',
    descEn: 'Decisively managed a national disaster with minimal loss.',
    icon: 'life-buoy',
    unlocked: false,
  },
  {
    id: 'ach_7',
    titleHi: 'आर्थिक सुधारक',
    titleEn: 'Economic Visionary',
    descHi: 'देश की GDP विकास दर को 8.5% से ऊपर पहुंचाया।',
    descEn: 'Elevated national GDP growth beyond 8.5%.',
    icon: 'trending-up',
    unlocked: false,
  }
];

export const TRAINING_PROGRAMS: TrainingProgram[] = [
  {
    id: 'tr_1',
    titleHi: 'जनसभा संबोधन व वाककला',
    titleEn: 'Public Speaking & Oratory',
    descHi: 'लाखों की भीड़ को प्रभावित करने और संवाद कौशल को निखारने का प्रशिक्षण।',
    descEn: 'Master crowd rhetoric, inspiring body language, and powerful delivery.',
    targetStat: 'communication',
    statBoost: 5,
    cost: 15000,
    timeDays: 2,
    energyCost: 20,
    icon: 'mic',
  },
  {
    id: 'tr_2',
    titleHi: 'रणनीति व चुनाव प्रबंधन',
    titleEn: 'Electoral Strategy & War Room',
    descHi: 'डेटा आधारित बूथ प्रबंधन और विरोधी दलों की चालों को भांपने की कला।',
    descEn: 'Learn micro-targeting, booth organization, and tactical counter-moves.',
    targetStat: 'strategy',
    statBoost: 5,
    cost: 25000,
    timeDays: 3,
    energyCost: 25,
    icon: 'compass',
  },
  {
    id: 'tr_3',
    titleHi: 'संकट व आपदा प्रबंधन',
    titleEn: 'Crisis Simulation Drill',
    descHi: 'अचानक उत्पन्न हुई आपात स्थिति में त्वरित व संतुलित फैसले लेने का अभ्यास।',
    descEn: 'Simulated high-pressure crisis response to protect lives and public trust.',
    targetStat: 'crisisManagement',
    statBoost: 6,
    cost: 30000,
    timeDays: 3,
    energyCost: 30,
    icon: 'shield-alert',
  },
  {
    id: 'tr_4',
    titleHi: 'प्रशासनिक व बजटीय दक्षता',
    titleEn: 'Public Administration & Budgeting',
    descHi: 'मंत्रालयों के कामकाज, फाइलों के त्वरित निपटारे और वित्तीय संतुलन का अध्ययन।',
    descEn: 'Master ministerial oversight, fiscal balancing, and efficient governance.',
    targetStat: 'administration',
    statBoost: 5,
    cost: 35000,
    timeDays: 4,
    energyCost: 25,
    icon: 'file-text',
  }
];
