import type { QuizQuestion } from '../types/quiz';

export const quizQuestions: QuizQuestion[] = [
  // 1-10: Fundamental Principles & Parliament Basics
  {
    id: 'q1',
    category: 'CONSTITUTION',
    difficulty: 'EASY',
    questionHi: 'भारतीय संविधान का मूल दर्शन और उद्देश्य किसमें समाहित है?',
    questionEn: 'The core philosophy and objectives of the Indian Constitution are enshrined in which part?',
    optionsHi: ['प्रस्तावना (Preamble)', 'मूल कर्तव्य', 'आपातकालीन प्रावधान', 'सातवीं अनुसूची'],
    optionsEn: ['The Preamble', 'Fundamental Duties', 'Emergency Provisions', 'Seventh Schedule'],
    correctIndex: 0,
    explanationHi: 'प्रस्तावना संविधान की आत्मा और मार्गदर्शक सिद्धांत है जो न्याय, स्वतंत्रता, समता और बंधुत्व की घोषणा करती है।',
    explanationEn: 'The Preamble serves as the soul and guiding spirit of the Constitution, declaring Justice, Liberty, Equality, and Fraternity.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 6
  },
  {
    id: 'q2',
    category: 'PARLIAMENT',
    difficulty: 'EASY',
    questionHi: 'लोकसभा में सरकार बनाने के लिए आवश्यक जादुई आंकड़ा (बहुमत) कितना है?',
    questionEn: 'What is the required majority mark to form a government in the 543-member Lok Sabha?',
    optionsHi: ['250', '272', '300', '315'],
    optionsEn: ['250', '272', '300', '315'],
    correctIndex: 1,
    explanationHi: 'कुल 543 निर्वाचित लोकसभा सीटों में से स्पष्ट बहुमत के लिए 272 या उससे अधिक सीटों का समर्थन आवश्यक होता है।',
    explanationEn: 'Out of 543 elected Lok Sabha seats, 272 or more seats constitute a simple majority to form the central government.',
    rewardStat: 'strategy',
    rewardAmount: 6
  },
  {
    id: 'q3',
    category: 'ELECTIONS',
    difficulty: 'EASY',
    questionHi: 'भारत में नागरिकों को मतदान करने का संवैधानिक अधिकार किस आयु पर प्राप्त होता है?',
    questionEn: 'At what age do Indian citizens attain the constitutional right to vote?',
    optionsHi: ['16 वर्ष', '18 वर्ष', '21 वर्ष', '25 वर्ष'],
    optionsEn: ['16 Years', '18 Years', '21 Years', '25 Years'],
    correctIndex: 1,
    explanationHi: '61वें संविधान संशोधन अधिनियम 1988 के तहत मतदान की न्यूनतम आयु 21 वर्ष से घटाकर 18 वर्ष कर दी गई थी।',
    explanationEn: 'The 61st Constitutional Amendment Act, 1988 lowered the voting age from 21 to 18 years.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 5
  },
  {
    id: 'q4',
    category: 'GOVERNANCE',
    difficulty: 'MEDIUM',
    questionHi: 'भारत के संविधान के अनुसार वास्तविक कार्यपालिका शक्तियां (Real Executive Power) किसके पास होती हैं?',
    questionEn: 'According to the Indian Constitution, real executive power is exercised by whom?',
    optionsHi: ['राष्ट्रपति', 'प्रधानमंत्री की अध्यक्षता में मंत्रिपरिषद', 'सर्वोच्च न्यायालय के मुख्य न्यायाधीश', 'संसद के सभापति'],
    optionsEn: ['The President', 'Council of Ministers headed by Prime Minister', 'Chief Justice of India', 'Speaker of Lok Sabha'],
    correctIndex: 1,
    explanationHi: 'राष्ट्रपति संवैधानिक प्रमुख (De Jure) होते हैं, परंतु वास्तविक कार्यपालिका शक्ति प्रधानमंत्री की अध्यक्षता वाली मंत्रिपरिषद (De Facto) के पास होती है।',
    explanationEn: 'The President is the nominal head, but de facto executive power rests with the Council of Ministers headed by the Prime Minister.',
    rewardStat: 'administration',
    rewardAmount: 7
  },
  {
    id: 'q5',
    category: 'ECONOMY',
    difficulty: 'MEDIUM',
    questionHi: 'केंद्रीय बजट (वार्षिक वित्तीय विवरण) संविधान के किस अनुच्छेद के तहत संसद में प्रस्तुत किया जाता है?',
    questionEn: 'Under which Article of the Constitution is the Annual Financial Statement (Union Budget) presented?',
    optionsHi: ['अनुच्छेद 110', 'अनुच्छेद 112', 'अनुच्छेद 123', 'अनुच्छेद 360'],
    optionsEn: ['Article 110', 'Article 112', 'Article 123', 'Article 360'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 112 के तहत राष्ट्रपति प्रत्येक वित्तीय वर्ष में संसद के दोनों सदनों के समक्ष वार्षिक वित्तीय विवरण रखवाते हैं।',
    explanationEn: 'Article 112 mandates the President to lay the Annual Financial Statement before both houses of Parliament.',
    rewardStat: 'finance',
    rewardAmount: 8
  },
  {
    id: 'q6',
    category: 'DEMOCRACY',
    difficulty: 'MEDIUM',
    questionHi: 'पंचायती राज व्यवस्था को संवैधानिक दर्जा किस संशोधन अधिनियम द्वारा दिया गया?',
    questionEn: 'Through which Constitutional Amendment Act was Panchayati Raj given constitutional status?',
    optionsHi: ['42वां संशोधन', '44वां संशोधन', '73वां संशोधन', '86वां संशोधन'],
    optionsEn: ['42nd Amendment', '44th Amendment', '73rd Amendment', '86th Amendment'],
    correctIndex: 2,
    explanationHi: '73वें संविधान संशोधन (1992) द्वारा त्रि-स्तरीय पंचायती राज को संवैधानिक मान्यता एवं 11वीं अनुसूची प्रदान की गई।',
    explanationEn: 'The 73rd Constitutional Amendment Act (1992) institutionalized the three-tier Panchayati Raj system and added 11th Schedule.',
    rewardStat: 'leadership',
    rewardAmount: 7
  },
  {
    id: 'q7',
    category: 'ELECTIONS',
    difficulty: 'HARD',
    questionHi: 'चुनाव की घोषणा के बाद लागू होने वाली "आदर्श आचार संहिता" (MCC) का मुख्य उद्देश्य क्या है?',
    questionEn: 'What is the primary objective of the Model Code of Conduct (MCC) enforced during elections?',
    optionsHi: [
      'सत्तारूढ़ दल को विशेष प्रचार अधिकार देना',
      'सभी दलों और प्रत्याशियों के लिए समान अवसर (Level Playing Field) और निष्पक्ष चुनाव सुनिश्चित करना',
      'विपक्ष के चुनाव प्रचार पर प्रतिबंध लगाना',
      'नागरिकों पर नया चुनावी कर लगाना'
    ],
    optionsEn: [
      'To give ruling parties special campaigning rights',
      'To guarantee a level playing field and free, fair elections for all parties and candidates',
      'To prohibit opposition campaigning',
      'To levy an electoral tax on citizens'
    ],
    correctIndex: 1,
    explanationHi: 'आदर्श आचार संहिता सभी उम्मीदवारों और दलों को समान अवसर देती है तथा सरकारी मशीनरी व लोक-लुभावन घोषणाओं के दुरुपयोग को रोकती है।',
    explanationEn: 'The Model Code of Conduct ensures ethical campaigning, prevents misuse of state resources, and guarantees equal footing.',
    rewardStat: 'publicTrust',
    rewardAmount: 8
  },
  {
    id: 'q8',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'धन विधेयक (Money Bill) केवल किस सदन में पहले पेश किया जा सकता है?',
    questionEn: 'A Money Bill can only be introduced first in which house of Parliament?',
    optionsHi: ['राज्यसभा', 'लोकसभा', 'विधान परिषद', 'किसी भी सदन में'],
    optionsEn: ['Rajya Sabha', 'Lok Sabha', 'Legislative Council', 'Either House'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 109 के अनुसार धन विधेयक केवल लोकसभा में राष्ट्रपति की पूर्व सिफारिश पर ही पेश किया जा सकता है, राज्यसभा इसे मात्र 14 दिन रोक सकती है।',
    explanationEn: 'Under Article 109, a Money Bill can only originate in the Lok Sabha with prior presidential recommendation.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 8
  },
  {
    id: 'q9',
    category: 'GOVERNANCE',
    difficulty: 'EXPERT',
    questionHi: 'संसद में "विश्वास मत" (Vote of Confidence) सिद्ध करने की आवश्यकता किसे होती है?',
    questionEn: 'Who is required to prove a Vote of Confidence on the floor of the Lok Sabha?',
    optionsHi: ['विपक्ष के नेता को', 'वर्तमान सरकार / प्रधानमंत्री को बहुमत सिद्ध करने हेतु', 'सर्वोच्च न्यायालय को', 'लोकसभा अध्यक्ष को'],
    optionsEn: ['The Leader of Opposition', 'The Prime Minister / Council of Ministers to prove their floor majority', 'The Supreme Court', 'The Lok Sabha Speaker'],
    correctIndex: 1,
    explanationHi: 'प्रधानमंत्री और उनकी मंत्रिपरिषद को लोकसभा के प्रति सामूहिक रूप से उत्तरदायी होने के कारण सदन में अपना बहुमत सिद्ध करना होता है।',
    explanationEn: 'The Prime Minister and Cabinet are collectively responsible to the Lok Sabha and must command the confidence of the house.',
    rewardStat: 'crisisManagement',
    rewardAmount: 10
  },
  {
    id: 'q10',
    category: 'ECONOMY',
    difficulty: 'EXPERT',
    questionHi: 'राजकोषीय घाटा (Fiscal Deficit) क्या दर्शाता है?',
    questionEn: 'What does the Fiscal Deficit of a nation indicate?',
    optionsHi: [
      'सरकार की कुल उधारी आवश्यकता (कुल व्यय - गैर-ऋण प्राप्तियां)',
      'केवल विदेशी कर्ज की मात्रा',
      'देश की कुल बचत',
      'बैंकों का सकल मुनाफा'
    ],
    optionsEn: [
      'Total government borrowing requirement (Total expenditure minus non-debt receipts)',
      'Only foreign external borrowing',
      'Total gross national savings',
      'Commercial banking profits'
    ],
    correctIndex: 0,
    explanationHi: 'राजकोषीय घाटा वह कुल धनराशि है जो सरकार को अपने खर्चों को पूरा करने के लिए उस वर्ष बाजार व अन्य स्रोतों से उधार लेनी पड़ती है।',
    explanationEn: 'Fiscal deficit represents the net borrowings required by the government to bridge the gap between revenue and expenditure.',
    rewardStat: 'finance',
    rewardAmount: 10
  },

  // 11-20: Constitutional Rights, Judiciary & Electoral Machinery
  {
    id: 'q11',
    category: 'CONSTITUTION',
    difficulty: 'EASY',
    questionHi: 'संविधान के किस अनुच्छेद को डॉ. बी.आर. अम्बेडकर ने "संविधान का हृदय और आत्मा" कहा था?',
    questionEn: 'Which Article of the Constitution was called the "Heart and Soul of the Constitution" by Dr. B.R. Ambedkar?',
    optionsHi: ['अनुच्छेद 14 (समानता)', 'अनुच्छेद 19 (स्वतंत्रता)', 'अनुच्छेद 21 (जीवन का अधिकार)', 'अनुच्छेद 32 (संवैधानिक उपचारों का अधिकार)'],
    optionsEn: ['Article 14 (Equality)', 'Article 19 (Freedom)', 'Article 21 (Right to Life)', 'Article 32 (Constitutional Remedies)'],
    correctIndex: 3,
    explanationHi: 'अनुच्छेद 32 नागरिकों को मौलिक अधिकारों के उल्लंघन पर सीधे सर्वोच्च न्यायालय जाने का अधिकार देता है (रिट याचिका)।',
    explanationEn: 'Article 32 guarantees the Right to Constitutional Remedies, empowering citizens to move the Supreme Court directly for enforcement of Fundamental Rights.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 6
  },
  {
    id: 'q12',
    category: 'ELECTIONS',
    difficulty: 'MEDIUM',
    questionHi: 'भारतीय निर्वाचन आयोग (ECI) की स्थापना संविधान के किस अनुच्छेद के तहत की गई है?',
    questionEn: 'Under which Article of the Constitution is the Election Commission of India (ECI) established?',
    optionsHi: ['अनुच्छेद 280', 'अनुच्छेद 324', 'अनुच्छेद 356', 'अनुच्छेद 370'],
    optionsEn: ['Article 280', 'Article 324', 'Article 356', 'Article 370'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 324 में संसद, राज्य विधानमंडलों, राष्ट्रपति और उपराष्ट्रपति के चुनावों के अधीक्षण, निर्देशन और नियंत्रण की शक्ति निर्वाचन आयोग में निहित है।',
    explanationEn: 'Article 324 vests superintendence, direction, and control of elections to Parliament, State Legislatures, and President/Vice-President in the ECI.',
    rewardStat: 'administration',
    rewardAmount: 7
  },
  {
    id: 'q13',
    category: 'ELECTIONS',
    difficulty: 'EASY',
    questionHi: 'मतदान में उपयोग होने वाली VVPAT मशीन का पूर्ण रूप क्या है?',
    questionEn: 'What is the full form of VVPAT machine used in electronic voting?',
    optionsHi: [
      'Voter Verifiable Paper Audit Trail',
      'Voter Verified Public Action Test',
      'Verified Voting Paper Authority Tool',
      'Voter Verification Parliamentary Audit Tab'
    ],
    optionsEn: [
      'Voter Verifiable Paper Audit Trail',
      'Voter Verified Public Action Test',
      'Verified Voting Paper Authority Tool',
      'Voter Verification Parliamentary Audit Tab'
    ],
    correctIndex: 0,
    explanationHi: 'VVPAT (Voter Verifiable Paper Audit Trail) मतदाता को 7 सेकंड तक पर्ची दिखाकर पुष्टि करता है कि उसका वोट सही प्रत्याशी को गया है।',
    explanationEn: 'VVPAT displays a printed slip for 7 seconds to reassure the voter that their vote has been cast correctly.',
    rewardStat: 'publicTrust',
    rewardAmount: 6
  },
  {
    id: 'q14',
    category: 'PARLIAMENT',
    difficulty: 'MEDIUM',
    questionHi: 'राज्यसभा का पदेन सभापति (Ex-Officio Chairman) कौन होता है?',
    questionEn: 'Who is the ex-officio Chairman of the Rajya Sabha (Council of States)?',
    optionsHi: ['भारत के राष्ट्रपति', 'भारत के उपराष्ट्रपति', 'प्रधानमंत्री', 'लोकसभा अध्यक्ष'],
    optionsEn: ['The President of India', 'The Vice-President of India', 'The Prime Minister', 'The Lok Sabha Speaker'],
    correctIndex: 1,
    explanationHi: 'संविधान के अनुच्छेद 64 और 89(1) के अनुसार भारत का उपराष्ट्रपति स्वतः ही राज्यसभा का पदेन सभापति होता है।',
    explanationEn: 'Under Articles 64 and 89(1), the Vice-President of India is the ex-officio Chairman of the Rajya Sabha.',
    rewardStat: 'leadership',
    rewardAmount: 6
  },
  {
    id: 'q15',
    category: 'CONSTITUTION',
    difficulty: 'HARD',
    questionHi: 'दल-बदल विरोधी कानून (Anti-Defection Law) संविधान की किस अनुसूची में जोड़ा गया है?',
    questionEn: 'The Anti-Defection Law is contained in which Schedule of the Indian Constitution?',
    optionsHi: ['आठवीं अनुसूची', 'नौवीं अनुसूची', 'दसवीं अनुसूची (10th Schedule)', 'ग्यारहवीं अनुसूची'],
    optionsEn: ['Eighth Schedule', 'Ninth Schedule', 'Tenth Schedule (10th Schedule)', 'Eleventh Schedule'],
    correctIndex: 2,
    explanationHi: '52वें संविधान संशोधन (1985) द्वारा दसवीं अनुसूची जोड़ी गई, जिसके तहत पार्टी व्हिप का उल्लंघन करने पर सांसदों/विधायकों की सदस्यता रद्द हो सकती है।',
    explanationEn: 'The 52nd Constitutional Amendment Act of 1985 added the 10th Schedule to disqualify legislators on grounds of defection.',
    rewardStat: 'strategy',
    rewardAmount: 8
  },
  {
    id: 'q16',
    category: 'GOVERNANCE',
    difficulty: 'HARD',
    questionHi: 'संसद में "प्रश्नकाल" (Question Hour) के तुरंत बाद का समय क्या कहलाता है?',
    questionEn: 'What is the period immediately following Question Hour in Parliament called?',
    optionsHi: ['शून्य काल (Zero Hour)', 'ध्यानाकर्षण प्रस्ताव', 'स्थगन काल', 'भोजन अवकाश'],
    optionsEn: ['Zero Hour', 'Calling Attention Motion', 'Adjournment Hour', 'Recess'],
    correctIndex: 0,
    explanationHi: 'शून्य काल (12:00 दोपहर) एक भारतीय संसदीय नवाचार है जिसमें सांसद बिना पूर्व सूचना के लोक महत्व के तात्कालिक मुद्दे उठा सकते हैं।',
    explanationEn: 'Zero Hour is an Indian parliamentary innovation where members can raise urgent matters of public importance without prior notice.',
    rewardStat: 'communication',
    rewardAmount: 7
  },
  {
    id: 'q17',
    category: 'CONSTITUTION',
    difficulty: 'EXPERT',
    questionHi: 'ऐतिहासिक "केशवानंद भारती बनाम केरल राज्य (1973)" मामले में सर्वोच्च न्यायालय ने क्या ऐतिहासिक सिद्धांत प्रतिपादित किया?',
    questionEn: 'What landmark doctrine was propounded by the Supreme Court in the Kesavananda Bharati case (1973)?',
    optionsHi: [
      'मूल संरचना का सिद्धांत (Basic Structure Doctrine)',
      'संसद की असीमित संशोधन शक्ति',
      'न्यायपालिका का कार्यपालिका में विलय',
      'मौलिक अधिकारों की पूर्ण समाप्ति'
    ],
    optionsEn: [
      'Basic Structure Doctrine',
      'Absolute Parliamentary Sovereignty',
      'Merger of Judiciary with Executive',
      'Abolition of Fundamental Rights'
    ],
    correctIndex: 0,
    explanationHi: '13 न्यायाधीशों की पीठ ने निर्णय दिया कि संसद संविधान के किसी भी हिस्से में संशोधन कर सकती है, परंतु उसके "मूल ढांचे" को नष्ट नहीं कर सकती।',
    explanationEn: 'A 13-judge bench held that Parliament can amend any part of the Constitution, but cannot alter its Basic Structure.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 10
  },
  {
    id: 'q18',
    category: 'ECONOMY',
    difficulty: 'MEDIUM',
    questionHi: 'भारत में वस्तु एवं सेवा कर (GST) किस संविधान संशोधन अधिनियम द्वारा लागू किया गया?',
    questionEn: 'Through which Constitutional Amendment Act was the Goods and Services Tax (GST) introduced?',
    optionsHi: ['99वां संशोधन', '100वां संशोधन', '101वां संशोधन', '103वां संशोधन'],
    optionsEn: ['99th Amendment', '100th Amendment', '101st Amendment', '103rd Amendment'],
    correctIndex: 2,
    explanationHi: '101वें संविधान संशोधन अधिनियम 2016 द्वारा 1 जुलाई 2017 से पूरे देश में "एक राष्ट्र, एक कर" के रूप में GST लागू हुआ।',
    explanationEn: 'The 101st Constitutional Amendment Act (2016) enabled nationwide implementation of GST from July 1, 2017.',
    rewardStat: 'finance',
    rewardAmount: 7
  },
  {
    id: 'q19',
    category: 'DEMOCRACY',
    difficulty: 'EASY',
    questionHi: 'मतदान में NOTA (None of the Above) विकल्प का क्या अर्थ है?',
    questionEn: 'What does the NOTA (None of the Above) option signify on an EVM ballot?',
    optionsHi: [
      'मतदाता चुनाव रद्द करना चाहता है',
      'मतदाता सूची में मौजूद किसी भी प्रत्याशी को वोट नहीं देना चाहता',
      'मतदान अधिकारी का गुप्त मत',
      'विजेता प्रत्याशी को दोगुना मत'
    ],
    optionsEn: [
      'The voter wants to cancel the election',
      'The voter chooses not to vote for any candidate in the fray',
      'The polling officer secret vote',
      'Double vote to the leading candidate'
    ],
    correctIndex: 1,
    explanationHi: 'सर्वोच्च न्यायालय के 2013 के आदेशानुसार मतदाताओं को सभी उम्मीदवारों को अस्वीकार करने का अधिकार देने हेतु NOTA बटन लाया गया।',
    explanationEn: 'Following a 2013 Supreme Court ruling, NOTA was introduced to allow voters to reject all contesting candidates.',
    rewardStat: 'publicTrust',
    rewardAmount: 5
  },
  {
    id: 'q20',
    category: 'GOVERNANCE',
    difficulty: 'HARD',
    questionHi: 'राष्ट्रपति द्वारा संसद का सत्र न चलने की स्थिति में अध्यादेश (Ordinance) जारी करने की शक्ति किस अनुच्छेद में है?',
    questionEn: 'Under which Article can the President promulgate an Ordinance when Parliament is in recess?',
    optionsHi: ['अनुच्छेद 72', 'अनुच्छेद 110', 'अनुच्छेद 123', 'अनुच्छेद 143'],
    optionsEn: ['Article 72', 'Article 110', 'Article 123', 'Article 143'],
    correctIndex: 2,
    explanationHi: 'अनुच्छेद 123 के तहत राष्ट्रपति अध्यादेश जारी कर सकते हैं, जिसे संसद का सत्र शुरू होने के 6 सप्ताह के भीतर दोनों सदनों से पारित कराना अनिवार्य होता है।',
    explanationEn: 'Article 123 empowers the President to issue Ordinances, which must be approved by Parliament within 6 weeks of reassembly.',
    rewardStat: 'crisisManagement',
    rewardAmount: 8
  },

  // 21-30: Parliament Operations, Finance & Emergency Powers
  {
    id: 'q21',
    category: 'PARLIAMENT',
    difficulty: 'MEDIUM',
    questionHi: 'संसद की बैठक आयोजित करने के लिए आवश्यक "गणपूर्ति" (Quorum) कुल सदस्य संख्या का कितना भाग है?',
    questionEn: 'What is the required Quorum to constitute a sitting of either House of Parliament?',
    optionsHi: ['1/5वां भाग (20%)', '1/10वां भाग (10%)', '1/3रा भाग (33%)', 'आधे सदस्य (50%)'],
    optionsEn: ['1/5th (20%)', '1/10th (10%)', '1/3rd (33%)', 'Half (50%)'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 100(3) के अनुसार सदन की बैठक के लिए कुल सदस्य संख्या का कम से कम 1/10वां भाग उपस्थित होना अनिवार्य है।',
    explanationEn: 'Under Article 100(3), the quorum for either House is 1/10th of the total membership.',
    rewardStat: 'administration',
    rewardAmount: 6
  },
  {
    id: 'q22',
    category: 'CONSTITUTION',
    difficulty: 'HARD',
    questionHi: 'राज्यों में संवैधानिक तंत्र विफल होने पर राष्ट्रपति शासन (President\'s Rule) किस अनुच्छेद के तहत लगाया जाता है?',
    questionEn: 'President\'s Rule in a State due to failure of constitutional machinery is imposed under which Article?',
    optionsHi: ['अनुच्छेद 352', 'अनुच्छेद 356', 'अनुच्छेद 360', 'अनुच्छेद 365'],
    optionsEn: ['Article 352', 'Article 356', 'Article 360', 'Article 365'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 356 राज्यपाल की रिपोर्ट या केंद्र के विवेक पर राज्य में संवैधानिक मशीनरी विफल होने पर राष्ट्रपति शासन की अनुमति देता है।',
    explanationEn: 'Article 356 enables the President to impose direct rule in a State upon failure of constitutional governance.',
    rewardStat: 'crisisManagement',
    rewardAmount: 8
  },
  {
    id: 'q23',
    category: 'CONSTITUTION',
    difficulty: 'MEDIUM',
    questionHi: 'राष्ट्रीय आपातकाल (National Emergency) संविधान के किस अनुच्छेद के तहत घोषित किया जा सकता है?',
    questionEn: 'A National Emergency can be proclaimed by the President under which Article?',
    optionsHi: ['अनुच्छेद 352', 'अनुच्छेद 356', 'अनुच्छेद 360', 'अनुच्छेद 368'],
    optionsEn: ['Article 352', 'Article 356', 'Article 360', 'Article 368'],
    correctIndex: 0,
    explanationHi: 'अनुच्छेद 352 के तहत युद्ध, बाह्य आक्रमण अथवा सशस्त्र विद्रोह की स्थिति में मंत्रिमंडल की लिखित सिफारिश पर राष्ट्रीय आपातकाल घोषित होता है।',
    explanationEn: 'Article 352 allows proclamation of National Emergency on grounds of war, external aggression, or armed rebellion.',
    rewardStat: 'leadership',
    rewardAmount: 7
  },
  {
    id: 'q24',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'संसद के दोनों सदनों की "संयुक्त बैठक" (Joint Sitting) की अध्यक्षता कौन करता है?',
    questionEn: 'Who presides over a Joint Sitting of both Houses of Parliament?',
    optionsHi: ['भारत के राष्ट्रपति', 'राज्यसभा के सभापति', 'लोकसभा अध्यक्ष (Speaker of Lok Sabha)', 'संसदीय कार्य मंत्री'],
    optionsEn: ['The President', 'Chairman of Rajya Sabha', 'Speaker of Lok Sabha', 'Minister of Parliamentary Affairs'],
    correctIndex: 2,
    explanationHi: 'अनुच्छेद 108 के तहत राष्ट्रपति संयुक्त बैठक बुलाते हैं, परंतु अनुच्छेद 118(4) के अनुसार इसकी अध्यक्षता लोकसभा अध्यक्ष करते हैं।',
    explanationEn: 'While the President convenes a Joint Sitting under Article 108, it is presided over by the Speaker of Lok Sabha under Article 118(4).',
    rewardStat: 'leadership',
    rewardAmount: 8
  },
  {
    id: 'q25',
    category: 'ECONOMY',
    difficulty: 'MEDIUM',
    questionHi: 'केंद्र और राज्यों के बीच कर राजस्व के बंटवारे की सिफारिश करने वाला संवैधानिक निकाय कौन सा है?',
    questionEn: 'Which constitutional body recommends the distribution of tax revenues between the Union and the States?',
    optionsHi: ['नीति आयोग', 'वित्त आयोग (Finance Commission)', 'जीएसटी परिषद', 'केंद्रीय सतर्कता आयोग'],
    optionsEn: ['NITI Aayog', 'Finance Commission', 'GST Council', 'Central Vigilance Commission'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 280 के तहत राष्ट्रपति प्रत्येक 5 वर्ष में वित्त आयोग का गठन करते हैं जो करों के बंटवारे की अनुशंसा करता है।',
    explanationEn: 'The Finance Commission is constituted every 5 years under Article 280 to recommend tax revenue devolution.',
    rewardStat: 'finance',
    rewardAmount: 7
  },
  {
    id: 'q26',
    category: 'GOVERNANCE',
    difficulty: 'EASY',
    questionHi: 'योजना आयोग (Planning Commission) के स्थान पर 2015 में किस नए थिंक-टैंक का गठन किया गया?',
    questionEn: 'Which think-tank was established in 2015 to replace the Planning Commission?',
    optionsHi: ['नीति आयोग (NITI Aayog)', 'राष्ट्रीय विकास परिषद', 'भारतीय प्रतिस्पर्धा आयोग', 'विधि आयोग'],
    optionsEn: ['NITI Aayog', 'National Development Council', 'Competition Commission of India', 'Law Commission'],
    correctIndex: 0,
    explanationHi: '1 जनवरी 2015 को नीति आयोग (National Institution for Transforming India) का गठन सहकारी संघवाद को बढ़ावा देने हेतु किया गया।',
    explanationEn: 'NITI Aayog (National Institution for Transforming India) was formed on January 1, 2015 to foster cooperative federalism.',
    rewardStat: 'administration',
    rewardAmount: 6
  },
  {
    id: 'q27',
    category: 'CONSTITUTION',
    difficulty: 'HARD',
    questionHi: '42वें संविधान संशोधन (1976) द्वारा संविधान की प्रस्तावना में कौन से तीन शब्द जोड़े गए थे?',
    questionEn: 'Which three words were added to the Preamble by the 42nd Constitutional Amendment (1976)?',
    optionsHi: [
      'समाजवादी, पंथनिरपेक्ष और अखंडता (Socialist, Secular, Integrity)',
      'स्वतंत्रता, समानता और बंधुत्व',
      'गणराज्य, न्याय और संप्रभुता',
      'लोकतांत्रिक, धर्मनिरपेक्ष और एकता'
    ],
    optionsEn: [
      'Socialist, Secular, and Integrity',
      'Liberty, Equality, and Fraternity',
      'Republic, Justice, and Sovereignty',
      'Democratic, Secular, and Unity'
    ],
    correctIndex: 0,
    explanationHi: '42वें संशोधन को "लघु संविधान" भी कहा जाता है, जिसने प्रस्तावना में समाजवादी, पंथनिरपेक्ष और अखंडता शब्द शामिल किए।',
    explanationEn: 'The 42nd Amendment (often called the Mini-Constitution) added "Socialist", "Secular", and "Integrity" to the Preamble.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 8
  },
  {
    id: 'q28',
    category: 'DEMOCRACY',
    difficulty: 'MEDIUM',
    questionHi: 'सूचना का अधिकार (RTI) अधिनियम भारत में किस वर्ष लागू हुआ था?',
    questionEn: 'In which year was the Right to Information (RTI) Act enacted in India?',
    optionsHi: ['2000', '2002', '2005', '2010'],
    optionsEn: ['2000', '2002', '2005', '2010'],
    correctIndex: 2,
    explanationHi: 'RTI अधिनियम 2005 नागरिकों को सरकारी कामकाज में पारदर्शिता और जवाबदेही सुनिश्चित करने का कानूनी अधिकार देता है।',
    explanationEn: 'The Right to Information Act, 2005 empowers citizens to seek information from public authorities, promoting transparency.',
    rewardStat: 'publicTrust',
    rewardAmount: 6
  },
  {
    id: 'q29',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'संसदीय व्यवस्था में राजनीतिक दल द्वारा अपने सांसदों को वोटिंग के समय अनिवार्य उपस्थिति हेतु जारी आदेश क्या कहलाता है?',
    questionEn: 'In parliamentary parlance, what is the formal written directive issued by a party to ensure MP attendance and voting called?',
    optionsHi: ['आदेश-पत्र', 'व्हिप (Whip)', 'अधिसूचना', 'संज्ञान'],
    optionsEn: ['Directive', 'Whip', 'Notification', 'Cognizance'],
    correctIndex: 1,
    explanationHi: 'व्हिप पार्टी के मुख्य सचेतक द्वारा जारी किया जाता है। थ्री-लाइन व्हिप का उल्लंघन दल-बदल विरोधी कानून के तहत अयोग्यता ला सकता है।',
    explanationEn: 'A Whip is an official directive; defying a three-line whip can lead to disqualification under the Anti-Defection Law.',
    rewardStat: 'strategy',
    rewardAmount: 8
  },
  {
    id: 'q30',
    category: 'GOVERNANCE',
    difficulty: 'MEDIUM',
    questionHi: 'भारत के नियंत्रक एवं महालेखा परीक्षक (CAG) का मुख्य संवैधानिक दायित्व क्या है?',
    questionEn: 'What is the primary constitutional duty of the Comptroller and Auditor General (CAG) of India?',
    optionsHi: [
      'नए कर लगाना',
      'केंद्र और राज्य सरकारों के सभी वित्तीय खर्चों का ऑडिट (लेखापरीक्षा) करना',
      'न्यायालयों में सरकार का प्रतिनिधित्व करना',
      'चुनावों का संचालन करना'
    ],
    optionsEn: [
      'To introduce new taxation',
      'To audit all receipts and expenditures of the Union and State governments',
      'To represent the government in courts',
      'To conduct national elections'
    ],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 148 के तहत CAG "सार्वजनिक धन का संरक्षक" (Guardian of Public Purse) होता है और अपनी रिपोर्ट संसद की लोक लेखा समिति को देता है।',
    explanationEn: 'Under Article 148, CAG audits government accounts and acts as the Guardian of the Public Purse.',
    rewardStat: 'finance',
    rewardAmount: 7
  },

  // 31-40: Local Self Governance, Judiciary & Electoral Dynamics
  {
    id: 'q31',
    category: 'DEMOCRACY',
    difficulty: 'EASY',
    questionHi: 'पंचायती राज व्यवस्था की आधारशिला क्या है, जिसमें गांव के सभी पंजीकृत मतदाता सदस्य होते हैं?',
    questionEn: 'What is the foundational pillar of Panchayati Raj, consisting of all registered voters of a village?',
    optionsHi: ['ग्राम पंचायत', 'ग्राम सभा (Gram Sabha)', 'पंचायत समिति', 'जिला परिषद'],
    optionsEn: ['Gram Panchayat', 'Gram Sabha', 'Panchayat Samiti', 'Zila Parishad'],
    correctIndex: 1,
    explanationHi: 'ग्राम सभा प्रत्यक्ष लोकतंत्र का उदाहरण है जहां गांव के सभी वयस्क मतदाता विकास योजनाओं और बजट की समीक्षा करते हैं।',
    explanationEn: 'The Gram Sabha is an organ of direct democracy comprising all adult registered voters in a village.',
    rewardStat: 'leadership',
    rewardAmount: 6
  },
  {
    id: 'q32',
    category: 'ELECTIONS',
    difficulty: 'HARD',
    questionHi: 'संसदीय और विधानसभा क्षेत्रों की सीमाओं का पुनर्निर्धारण कौन सा आयोग करता है?',
    questionEn: 'Which commission is responsible for redrawing the boundaries of parliamentary and assembly constituencies?',
    optionsHi: ['विधि आयोग', 'परिसीमन आयोग (Delimitation Commission)', 'मानवाधिकार आयोग', 'वित्त आयोग'],
    optionsEn: ['Law Commission', 'Delimitation Commission', 'Human Rights Commission', 'Finance Commission'],
    correctIndex: 1,
    explanationHi: 'परिसीमन आयोग नवीनतम जनगणना के आधार पर जनसंख्या के अनुपात में सीटों की सीमाओं का न्यायसंगत सीमांकन करता है।',
    explanationEn: 'The Delimitation Commission redraws constituency boundaries to ensure balanced demographic representation.',
    rewardStat: 'strategy',
    rewardAmount: 8
  },
  {
    id: 'q33',
    category: 'CONSTITUTION',
    difficulty: 'MEDIUM',
    questionHi: 'संसद में 86वें संशोधन अधिनियम (2002) द्वारा किस अधिकार को मौलिक अधिकार (अनुच्छेद 21A) बनाया गया?',
    questionEn: 'Which right was incorporated as Fundamental Right under Article 21A by the 86th Constitutional Amendment (2002)?',
    optionsHi: ['काम पाने का अधिकार', '6 से 14 वर्ष के बच्चों को मुफ्त व अनिवार्य शिक्षा का अधिकार', 'इंटरनेट का अधिकार', 'समान काम के लिए समान वेतन'],
    optionsEn: ['Right to Work', 'Right to Free and Compulsory Education for children aged 6 to 14 years', 'Right to High-speed Internet', 'Equal Pay for Equal Work'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 21A के तहत 6 से 14 वर्ष के प्रत्येक बच्चे को प्रारंभिक शिक्षा प्राप्त करना मौलिक अधिकार बना दिया गया।',
    explanationEn: 'Under Article 21A, free and compulsory education for all children between 6 and 14 years was made a Fundamental Right.',
    rewardStat: 'publicTrust',
    rewardAmount: 7
  },
  {
    id: 'q34',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'लोकसभा में विपक्ष के नेता (Leader of Opposition) का दर्जा पाने हेतु किसी दल के पास न्यूनतम कितनी सीटें होनी चाहिए?',
    questionEn: 'To be officially recognized as the Leader of Opposition in Lok Sabha, a party must secure what minimum share of seats?',
    optionsHi: ['कुल सीटों का 5%', 'कुल सीटों का 10% (कम से कम 55 सीटें)', 'कुल सीटों का 15%', 'कुल सीटों का 25%'],
    optionsEn: ['5% of total seats', '10% of total seats (at least 55 seats)', '15% of total seats', '25% of total seats'],
    correctIndex: 1,
    explanationHi: 'नियमों के अनुसार मुख्य विपक्षी दल को सदन की कुल सदस्य संख्या का कम से कम 10% (543 में से 55 सीटें) जीतना आवश्यक होता है।',
    explanationEn: 'Under parliamentary rules, an opposition party must hold at least 10% of the total house strength (55 seats) to claim the Leader of Opposition post.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 8
  },
  {
    id: 'q35',
    category: 'GOVERNANCE',
    difficulty: 'EXPERT',
    questionHi: 'भारत सरकार का सर्वोच्च विधिक अधिकारी (Chief Legal Advisor) कौन होता है?',
    questionEn: 'Who is the highest law officer and chief legal advisor to the Government of India?',
    optionsHi: ['सर्वोच्च न्यायालय के मुख्य न्यायाधीश', 'महान्यायवादी (Attorney General of India)', 'सॉलिसिटर जनरल', 'केंद्रीय विधि सचिव'],
    optionsEn: ['Chief Justice of India', 'Attorney General of India', 'Solicitor General of India', 'Union Law Secretary'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 76 के तहत राष्ट्रपति द्वारा नियुक्त भारत का महान्यायवादी (Attorney General) सरकार का मुख्य कानूनी सलाहकार होता है और उसे संसद में बोलने का अधिकार होता है।',
    explanationEn: 'Article 76 provides for the Attorney General of India, who advises the union government on legal matters and has the right of audience in all courts.',
    rewardStat: 'administration',
    rewardAmount: 9
  },
  {
    id: 'q36',
    category: 'ECONOMY',
    difficulty: 'HARD',
    questionHi: 'भारतीय रिजर्व बैंक (RBI) की मौद्रिक नीति समिति (MPC) में कितने सदस्य होते हैं?',
    questionEn: 'How many members constitute the Monetary Policy Committee (MPC) of the Reserve Bank of India?',
    optionsHi: ['4 सदस्य', '5 सदस्य', '6 सदस्य', '8 सदस्य'],
    optionsEn: ['4 Members', '5 Members', '6 Members', '8 Members'],
    correctIndex: 2,
    explanationHi: 'MPC में कुल 6 सदस्य होते हैं: 3 RBI से (गवर्नर सहित) और 3 केंद्र सरकार द्वारा नामित विशेषज्ञ। इसका कार्य मुद्रास्फीति लक्ष्य प्राप्त करना है।',
    explanationEn: 'The MPC comprises 6 members (3 from RBI including Governor, and 3 government nominees) to set policy repo rates.',
    rewardStat: 'finance',
    rewardAmount: 8
  },
  {
    id: 'q37',
    category: 'DEMOCRACY',
    difficulty: 'MEDIUM',
    questionHi: 'जनहित याचिका (Public Interest Litigation - PIL) की अवधारणा भारत में किसके द्वारा लोकप्रिय की गई?',
    questionEn: 'The concept of Public Interest Litigation (PIL) in India was pioneered and popularized by which Chief Justice?',
    optionsHi: ['न्यायमूर्ति पी.एन. भगवती व वी.आर. कृष्ण अय्यर', 'न्यायमूर्ति जे.एस. वर्मा', 'न्यायमूर्ति दीपक मिश्रा', 'न्यायमूर्ति रंजन गोगोई'],
    optionsEn: ['Justice P.N. Bhagwati & Justice V.R. Krishna Iyer', 'Justice J.S. Verma', 'Justice Dipak Misra', 'Justice Ranjan Gogoi'],
    correctIndex: 0,
    explanationHi: '1980 के दशक में न्यायमूर्ति पी.एन. भगवती और वी.आर. कृष्ण अय्यर ने गरीबों और वंचितों को न्याय दिलाने हेतु PIL की शुरुआत की।',
    explanationEn: 'Justices P.N. Bhagwati and V.R. Krishna Iyer pioneered PIL in the early 1980s to expand access to justice.',
    rewardStat: 'publicTrust',
    rewardAmount: 7
  },
  {
    id: 'q38',
    category: 'ELECTIONS',
    difficulty: 'MEDIUM',
    questionHi: 'भारत में पहली बार लोकसभा के आम चुनाव कब संपन्न हुए थे?',
    questionEn: 'When were the first General Elections to the Lok Sabha held in independent India?',
    optionsHi: ['1947-48', '1950', '1951-52', '1955'],
    optionsEn: ['1947-48', '1950', '1951-52', '1955'],
    correctIndex: 2,
    explanationHi: 'अक्टूबर 1951 से फरवरी 1952 के बीच भारत के पहले आम चुनाव ऐतिहासिक स्तर पर सुकुमार सेन की देखरेख में संपन्न हुए थे।',
    explanationEn: 'India\'s first General Elections took place between October 1951 and February 1952 under first CEC Sukumar Sen.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 6
  },
  {
    id: 'q39',
    category: 'CONSTITUTION',
    difficulty: 'EXPERT',
    questionHi: 'संविधान की सातवीं अनुसूची में केंद्र और राज्यों के बीच शक्तियों का विभाजन किन तीन सूचियों में किया गया है?',
    questionEn: 'Under the Seventh Schedule, legislative powers between Union and States are divided into which three lists?',
    optionsHi: [
      'संघ सूची, राज्य सूची, समवर्ती सूची (Union, State, Concurrent)',
      'केंद्रीय सूची, जिला सूची, ग्राम सूची',
      'नागरिक सूची, सैनिक सूची, वाणिज्य सूची',
      'प्राथमिक सूची, माध्यमिक सूची, तृतीयक सूची'
    ],
    optionsEn: [
      'Union List, State List, Concurrent List',
      'Central List, District List, Village List',
      'Civil List, Military List, Commercial List',
      'Primary List, Secondary List, Tertiary List'
    ],
    correctIndex: 0,
    explanationHi: 'अनुच्छेद 246 के तहत संघ सूची (केंद्र), राज्य सूची (राज्य), और समवर्ती सूची (दोनों, केंद्र के कानून को वरीयता) में विषयों का बंटवारा है।',
    explanationEn: 'Article 246 divides powers across Union List, State List, and Concurrent List (Union prevailing in case of conflict).',
    rewardStat: 'administration',
    rewardAmount: 9
  },
  {
    id: 'q40',
    category: 'PARLIAMENT',
    difficulty: 'MEDIUM',
    questionHi: 'नवनिर्वाचित लोकसभा के पहले सत्र में नवनिर्वाचित सांसदों को शपथ दिलाने हेतु किसे नियुक्त किया जाता है?',
    questionEn: 'Who is appointed by the President to administer oath to newly elected MPs in the inaugural Lok Sabha session?',
    optionsHi: ['उपराष्ट्रपति', 'प्रोटेम स्पीकर (Pro-tem Speaker)', 'प्रधानमंत्री', 'मुख्य चुनाव आयुक्त'],
    optionsEn: ['The Vice-President', 'Pro-tem Speaker', 'The Prime Minister', 'Chief Election Commissioner'],
    correctIndex: 1,
    explanationHi: 'सदन के वरिष्ठतम सांसदों में से राष्ट्रपति प्रोटेम स्पीकर नियुक्त करते हैं जो सांसदों को शपथ दिलाते हैं और नए स्पीकर के चुनाव का संचालन करते हैं।',
    explanationEn: 'The President appoints a senior MP as Pro-tem Speaker to administer oath to members and oversee election of the Speaker.',
    rewardStat: 'leadership',
    rewardAmount: 7
  },

  // 41-50: Cabinet Strategy, Coalition Politics & State Governance
  {
    id: 'q41',
    category: 'GOVERNANCE',
    difficulty: 'HARD',
    questionHi: 'भारत के राष्ट्रपति का चुनाव किस निर्वाचक मंडल (Electoral College) द्वारा संपन्न होता है?',
    questionEn: 'The President of India is elected by an Electoral College consisting of whom?',
    optionsHi: [
      'केवल लोकसभा के सभी सदस्य',
      'संसद के दोनों सदनों के निर्वाचित सदस्य तथा राज्यों/दिल्ली/पुदुचेरी की विधानसभाओं के निर्वाचित सदस्य',
      'देश के सभी प्रत्यक्ष मतदाता',
      'केवल राज्यों के मुख्यमंत्री और राज्यपाल'
    ],
    optionsEn: [
      'Only all members of Lok Sabha',
      'Elected members of both Houses of Parliament and elected members of State Legislative Assemblies (including Delhi & Puducherry)',
      'All eligible direct citizens of India',
      'Only State Chief Ministers and Governors'
    ],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 54 के तहत राष्ट्रपति के चुनाव में संसद और विधानसभाओं के केवल निर्वाचित (Elected) सदस्य ही मतदान करते हैं, मनोनीत सदस्य नहीं।',
    explanationEn: 'Article 54 provides that only elected members of Parliament and State Legislative Assemblies can vote in the Presidential election.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 8
  },
  {
    id: 'q42',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'संसद में "अविश्वास प्रस्ताव" (No-Confidence Motion) लाने के लिए न्यूनतम कितने लोकसभा सदस्यों का समर्थन आवश्यक है?',
    questionEn: 'How many Lok Sabha members must support a No-Confidence Motion for it to be admitted for debate?',
    optionsHi: ['25 सदस्य', '50 सदस्य', '75 सदस्य', '100 सदस्य'],
    optionsEn: ['25 Members', '50 Members', '75 Members', '100 Members'],
    correctIndex: 1,
    explanationHi: 'लोकसभा नियम 198 के तहत अविश्वास प्रस्ताव पेश करने हेतु कम से कम 50 सांसदों का लिखित समर्थन आवश्यक होता है।',
    explanationEn: 'Under Rule 198 of Lok Sabha procedure, a No-Confidence Motion requires the backing of at least 50 members to be admitted.',
    rewardStat: 'strategy',
    rewardAmount: 8
  },
  {
    id: 'q43',
    category: 'CONSTITUTION',
    difficulty: 'MEDIUM',
    questionHi: 'संविधान में संशोधन की प्रक्रिया किस अनुच्छेद में वर्णित है?',
    questionEn: 'The procedure for amending the Indian Constitution is laid down in which Article?',
    optionsHi: ['अनुच्छेद 356', 'अनुच्छेद 360', 'अनुच्छेद 368', 'अनुच्छेद 371'],
    optionsEn: ['Article 356', 'Article 360', 'Article 368', 'Article 371'],
    correctIndex: 2,
    explanationHi: 'अनुच्छेद 368 संसद को संविधान के उपबंधों को संशोधित करने की शक्ति और प्रक्रिया प्रदान करता है (साधारण, विशेष, अथवा राज्यों की सहमति वाला बहुमत)।',
    explanationEn: 'Article 368 in Part XX of the Constitution deals with the powers of Parliament to amend the Constitution and procedure thereof.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 7
  },
  {
    id: 'q44',
    category: 'GOVERNANCE',
    difficulty: 'HARD',
    questionHi: 'भारत के प्रशासनिक तंत्र में सर्वोच्च पदस्थ लोक सेवक (Senior-most Civil Servant) कौन होता है?',
    questionEn: 'Who is the senior-most civil servant and head of the civil services in the Government of India?',
    optionsHi: ['गृह सचिव', 'कैबिनेट सचिव (Cabinet Secretary)', 'प्रधानमंत्री के प्रधान सचिव', 'विदेश सचिव'],
    optionsEn: ['Union Home Secretary', 'Cabinet Secretary', 'Principal Secretary to the Prime Minister', 'Foreign Secretary'],
    correctIndex: 1,
    explanationHi: 'कैबिनेट सचिव कैबिनेट सचिवालय के प्रशासनिक प्रमुख और सिविल सेवा बोर्ड के पदेन अध्यक्ष होते हैं, जो सीधे प्रधानमंत्री को रिपोर्ट करते हैं।',
    explanationEn: 'The Cabinet Secretary is the highest-ranking executive official and senior-most civil servant in India.',
    rewardStat: 'administration',
    rewardAmount: 8
  },
  {
    id: 'q45',
    category: 'ECONOMY',
    difficulty: 'EASY',
    questionHi: 'भारत में वित्तीय वर्ष (Financial Year) किस अवधि के दौरान चलता है?',
    questionEn: 'What is the duration of the Financial Year in India?',
    optionsHi: ['1 जनवरी से 31 दिसंबर', '1 अप्रैल से 31 मार्च', '1 जुलाई से 30 जून', '1 अक्टूबर से 30 सितंबर'],
    optionsEn: ['1 January to 31 December', '1 April to 31 March', '1 July to 30 June', '1 October to 30 September'],
    correctIndex: 1,
    explanationHi: 'भारत में वित्तीय वर्ष प्रतिवर्ष 1 अप्रैल से प्रारंभ होकर अगले वर्ष के 31 मार्च को समाप्त होता है।',
    explanationEn: 'The Indian financial year runs from 1 April to 31 March of the subsequent year.',
    rewardStat: 'finance',
    rewardAmount: 5
  },
  {
    id: 'q46',
    category: 'ELECTIONS',
    difficulty: 'HARD',
    questionHi: 'जनप्रतिनिधित्व अधिनियम 1951 की किस धारा के तहत 2 वर्ष या अधिक की सजा पाने वाले सांसद/विधायक तुरंत अयोग्य हो जाते हैं?',
    questionEn: 'Under which section of Representation of the People Act, 1951 is an MP/MLA disqualified upon a conviction of 2 or more years?',
    optionsHi: ['धारा 8(3)', 'धारा 123', 'धारा 77', 'धारा 15'],
    optionsEn: ['Section 8(3)', 'Section 123', 'Section 77', 'Section 15'],
    correctIndex: 0,
    explanationHi: 'धारा 8(3) और लिली थॉमस केस (2013) के तहत 2 वर्ष या उससे अधिक की जेल की सजा होते ही जनप्रतिनिधि की सदस्यता तुरंत समाप्त हो जाती है।',
    explanationEn: 'Under Section 8(3) as interpreted in Lily Thomas (2013), a lawmaker convicted for 2+ years is disqualified immediately.',
    rewardStat: 'crisisManagement',
    rewardAmount: 9
  },
  {
    id: 'q47',
    category: 'DEMOCRACY',
    difficulty: 'MEDIUM',
    questionHi: 'शहरी स्थानीय निकायों (नगर निगम, नगरपालिका) को संवैधानिक दर्जा किस संशोधन से मिला?',
    questionEn: 'Which Constitutional Amendment Act granted constitutional status to Urban Local Bodies (Municipalities)?',
    optionsHi: ['71वां संशोधन', '72वां संशोधन', '73वां संशोधन', '74वां संशोधन'],
    optionsEn: ['71st Amendment', '72nd Amendment', '73rd Amendment', '74th Amendment'],
    correctIndex: 3,
    explanationHi: '74वें संविधान संशोधन अधिनियम (1992) द्वारा संविधान में भाग IX-A और 12वीं अनुसूची जोड़कर नगरपालिकाओं को संवैधानिक रूप दिया गया।',
    explanationEn: 'The 74th Amendment Act of 1992 added Part IX-A and the 12th Schedule for urban local governance.',
    rewardStat: 'leadership',
    rewardAmount: 7
  },
  {
    id: 'q48',
    category: 'CONSTITUTION',
    difficulty: 'EASY',
    questionHi: 'संविधान सभा ने भारत के संविधान को किस तिथि को अंगीकृत (Adopt) किया था?',
    questionEn: 'On which date was the Constitution of India formally adopted by the Constituent Assembly?',
    optionsHi: ['15 अगस्त 1947', '26 नवंबर 1949', '26 जनवरी 1950', '2 अक्टूबर 1948'],
    optionsEn: ['15 August 1947', '26 November 1949', '26 January 1950', '2 October 1948'],
    correctIndex: 1,
    explanationHi: 'संविधान 26 नवंबर 1949 को अंगीकृत किया गया (जिसे संविधान दिवस के रूप में मनाया जाता है) और 26 जनवरी 1950 को पूर्णतः लागू हुआ।',
    explanationEn: 'The Constitution was adopted on 26 November 1949 (Constitution Day) and came into full effect on 26 January 1950.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 5
  },
  {
    id: 'q49',
    category: 'PARLIAMENT',
    difficulty: 'MEDIUM',
    questionHi: 'संसद में "तारांकित प्रश्न" (Starred Question) का उत्तर मंत्री द्वारा किस रूप में दिया जाता है?',
    questionEn: 'In what form is an oral answer given by a Minister to a Starred Question in Parliament?',
    optionsHi: ['लिखित रूप में', 'मौखिक रूप में (जिस पर पूरक प्रश्न पूछे जा सकते हैं)', 'सीक्रेट लिफाफे में', 'प्रेस नोट द्वारा'],
    optionsEn: ['In writing on the table', 'Orally on the floor of the House (allowing supplementary questions)', 'In sealed confidential cover', 'Via Press Release'],
    correctIndex: 1,
    explanationHi: 'तारांकित प्रश्नों पर तारा (*) का निशान होता है, इनका मौखिक उत्तर दिया जाता है तथा पूरक प्रश्न (Supplementary Questions) पूछे जा सकते हैं।',
    explanationEn: 'A Starred Question is marked with an asterisk and answered orally in the House, permitting supplementary questions.',
    rewardStat: 'communication',
    rewardAmount: 7
  },
  {
    id: 'q50',
    category: 'GOVERNANCE',
    difficulty: 'HARD',
    questionHi: 'राज्यों में राज्यपाल की नियुक्ति संविधान के किस अनुच्छेद के तहत राष्ट्रपति द्वारा की जाती है?',
    questionEn: 'Under which Article of the Constitution is a Governor appointed to a State by the President?',
    optionsHi: ['अनुच्छेद 153', 'अनुच्छेद 155', 'अनुच्छेद 163', 'अनुच्छेद 200'],
    optionsEn: ['Article 153', 'Article 155', 'Article 163', 'Article 200'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 155 के अनुसार राज्य के राज्यपाल को राष्ट्रपति अपने हस्ताक्षर और मुद्रा सहित अधिपत्र द्वारा नियुक्त करते हैं।',
    explanationEn: 'Article 155 provides that the Governor of a State shall be appointed by the President by warrant under hand and seal.',
    rewardStat: 'administration',
    rewardAmount: 8
  },

  // 51-65: Advanced Constitutional Amendments, Economic Policy & Electoral Ethics
  {
    id: 'q51',
    category: 'CONSTITUTION',
    difficulty: 'HARD',
    questionHi: 'समान नागरिक संहिता (Uniform Civil Code - UCC) संविधान के किस अनुच्छेद में राज्य के नीति निर्देशक तत्व के रूप में उल्लिखित है?',
    questionEn: 'The Uniform Civil Code (UCC) is mentioned in which Article under Directive Principles of State Policy?',
    optionsHi: ['अनुच्छेद 40', 'अनुच्छेद 44', 'अनुच्छेद 48', 'अनुच्छेद 51A'],
    optionsEn: ['Article 40', 'Article 44', 'Article 48', 'Article 51A'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 44 कहता है कि राज्य भारत के पूरे क्षेत्र में नागरिकों के लिए एक समान नागरिक संहिता सुनिश्चित करने का प्रयास करेगा।',
    explanationEn: 'Article 44 of the Constitution directs the State to endeavor to secure for citizens a Uniform Civil Code throughout the territory of India.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 8
  },
  {
    id: 'q52',
    category: 'ELECTIONS',
    difficulty: 'EXPERT',
    questionHi: 'चुनाव चिन्ह (आरक्षण और आवंटन) आदेश 1968 के तहत यदि किसी पार्टी में विभाजन होता है, तो पार्टी नाम व चुनाव चिन्ह का निर्णय कौन करता है?',
    questionEn: 'Under the Election Symbols (Reservation and Allotment) Order, 1968, who adjudicates disputes over party symbol upon a split?',
    optionsHi: ['सर्वोच्च न्यायालय', 'भारत का निर्वाचन आयोग (ECI)', 'संसद की विशेषाधिकार समिति', 'गृह मंत्रालय'],
    optionsEn: ['The Supreme Court', 'The Election Commission of India (ECI)', 'Privileges Committee of Parliament', 'Ministry of Home Affairs'],
    correctIndex: 1,
    explanationHi: 'पैराग्राफ 15 के तहत चुनाव आयोग दोनों गुटों के सांसदों/विधायकों व संगठन पदाधिकारियों के बहुमत परीक्षण के आधार पर सिंबल का फैसला करता है।',
    explanationEn: 'Under Paragraph 15 of the 1968 Order, the ECI alone decides which faction constitutes the recognized political party based on test of majority.',
    rewardStat: 'strategy',
    rewardAmount: 10
  },
  {
    id: 'q53',
    category: 'ECONOMY',
    difficulty: 'HARD',
    questionHi: 'GST परिषद (GST Council) की अध्यक्षता कौन करता है?',
    questionEn: 'Who chairs the GST Council constituted under Article 279A of the Constitution?',
    optionsHi: ['प्रधानमंत्री', 'केंद्रीय वित्त मंत्री', 'RBI गवर्नर', 'नीति आयोग के उपाध्यक्ष'],
    optionsEn: ['The Prime Minister', 'Union Finance Minister', 'Governor of RBI', 'Vice-Chairman of NITI Aayog'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 279A के तहत केंद्रीय वित्त मंत्री GST परिषद के अध्यक्ष होते हैं और सभी राज्यों के वित्त मंत्री इसके सदस्य होते हैं।',
    explanationEn: 'The Union Finance Minister chairs the GST Council, with State Finance Ministers acting as members.',
    rewardStat: 'finance',
    rewardAmount: 8
  },
  {
    id: 'q54',
    category: 'DEMOCRACY',
    difficulty: 'HARD',
    questionHi: 'भ्रष्टाचार की जांच हेतु स्वतंत्र लोकपाल (Lokpal) का गठन किस अधिनियम के अंतर्गत हुआ?',
    questionEn: 'The independent anti-corruption ombudsman Lokpal was established under which Act?',
    optionsHi: ['भ्रष्टाचार निवारण अधिनियम 1988', 'लोकपाल और लोकायुक्त अधिनियम 2013', 'सूचना का अधिकार अधिनियम 2005', 'नागरिक सुरक्षा अधिनियम'],
    optionsEn: ['Prevention of Corruption Act 1988', 'Lokpal and Lokayuktas Act, 2013', 'Right to Information Act 2005', 'Civil Defence Act'],
    correctIndex: 1,
    explanationHi: 'लोकपाल और लोकायुक्त अधिनियम 2013 के तहत सार्वजनिक सेवकों व प्रधानमंत्री तक के खिलाफ भ्रष्टाचार के आरोपों की जांच हेतु लोकपाल बना।',
    explanationEn: 'The Lokpal and Lokayuktas Act, 2013 established an ombudsman to inquire into corruption allegations against public functionaries.',
    rewardStat: 'publicTrust',
    rewardAmount: 8
  },
  {
    id: 'q55',
    category: 'PARLIAMENT',
    difficulty: 'MEDIUM',
    questionHi: 'संसद में बजट चर्चा के दौरान जब समय की कमी के कारण सभी बची हुई अनुदान मांगों को बिना चर्चा के सीधे मतदान हेतु रख दिया जाता है, तो उसे क्या कहते हैं?',
    questionEn: 'In parliamentary budget procedure, putting all outstanding demands for grants to vote without discussion due to time limits is called?',
    optionsHi: ['गिलोटिन (Guillotine)', 'कट मोशन', 'स्थगन प्रस्ताव', 'साइन डाई'],
    optionsEn: ['Guillotine', 'Cut Motion', 'Adjournment Motion', 'Sine Die'],
    correctIndex: 0,
    explanationHi: 'गिलोटिन वह संसदीय प्रक्रिया है जिसमें अंतिम दिन बची हुई सभी वित्तीय मांगों को एक साथ बिना आगे बहस के पास करने के लिए रख दिया जाता है।',
    explanationEn: 'Guillotine refers to the parliamentary guillotine procedure where pending budget grant demands are put to vote en masse.',
    rewardStat: 'administration',
    rewardAmount: 7
  },
  {
    id: 'q56',
    category: 'CONSTITUTION',
    difficulty: 'MEDIUM',
    questionHi: '103वें संविधान संशोधन अधिनियम (2019) द्वारा सामान्य वर्ग के आर्थिक रूप से कमजोर (EWS) नागरिकों को कितना आरक्षण प्रदान किया गया?',
    questionEn: 'What percentage of reservation was granted to Economically Weaker Sections (EWS) by the 103rd Constitutional Amendment Act (2019)?',
    optionsHi: ['5%', '10%', '15%', '27%'],
    optionsEn: ['5%', '10%', '15%', '27%'],
    correctIndex: 1,
    explanationHi: '103वें संशोधन ने अनुच्छेद 15(6) और 16(6) जोड़कर गैर-आरक्षित वर्ग के EWS नागरिकों को शिक्षा और सरकारी नौकरियों में 10% आरक्षण दिया।',
    explanationEn: 'The 103rd Amendment inserted Articles 15(6) and 16(6) providing up to 10% reservation for EWS in jobs and educational institutions.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 7
  },
  {
    id: 'q57',
    category: 'ELECTIONS',
    difficulty: 'HARD',
    questionHi: 'जनप्रतिनिधित्व अधिनियम 1951 के तहत चुनाव के सभी चरणों के मतदान समाप्त होने तक किस पर पूर्ण प्रतिबंध होता है?',
    questionEn: 'Under Section 126A of Representation of the People Act, what is strictly prohibited until the close of polling across all phases?',
    optionsHi: ['प्रेस कॉन्फ्रेंस', 'एग्जिट पोल (Exit Poll) का प्रसारण व प्रकाशन', 'राजनीतिक दलों की आम सभा', 'पोस्टर लगाना'],
    optionsEn: ['Press Conferences', 'Broadcasting and publishing of Exit Polls', 'Party general meetings', 'Pasting posters'],
    correctIndex: 1,
    explanationHi: 'मतदाताओं की राय को निष्पक्ष बनाए रखने के लिए अंतिम चरण के मतदान का समय समाप्त होने तक एग्जिट पोल का प्रसारण पूर्णतः प्रतिबंधित रहता है।',
    explanationEn: 'Section 126A bans conducting and disseminating exit poll results through print or electronic media during the election window.',
    rewardStat: 'publicTrust',
    rewardAmount: 8
  },
  {
    id: 'q58',
    category: 'GOVERNANCE',
    difficulty: 'EXPERT',
    questionHi: 'राज्य सरकार और विधानसभा के मध्य बहुमत विवाद होने पर सरकार का बहुमत सिद्ध करने का एकमात्र वैध मंच क्या है?',
    questionEn: 'In case of majority claims or disputes, what is the only constitutionally recognized test according to S.R. Bommai case (1994)?',
    optionsHi: ['राज्यपाल के आवास पर विधायकों की परेड', 'सदन का पटल (Floor Test in Assembly)', 'प्रेस वार्ता', 'हस्ताक्षर युक्त ज्ञापन'],
    optionsEn: ['Parade of MLAs at Raj Bhavan', 'Floor Test in the Legislative Assembly', 'Press Conference', 'Signed Memorandum'],
    correctIndex: 1,
    explanationHi: 'एस.आर. बोम्मई केस (1994) में सर्वोच्च न्यायालय ने स्पष्ट व्यवस्था दी कि बहुमत का परीक्षण केवल और केवल सदन के पटल (Floor Test) पर ही हो सकता है।',
    explanationEn: 'In S.R. Bommai (1994), the Supreme Court ruled that the only constitutionally valid method to test majority is on the floor of the House.',
    rewardStat: 'crisisManagement',
    rewardAmount: 10
  },
  {
    id: 'q59',
    category: 'PARLIAMENT',
    difficulty: 'EASY',
    questionHi: 'राज्यसभा के सदस्यों का कार्यकाल कितने वर्षों का होता है?',
    questionEn: 'What is the tenure of a member of the Rajya Sabha?',
    optionsHi: ['4 वर्ष', '5 वर्ष', '6 वर्ष', 'आजीवन'],
    optionsEn: ['4 Years', '5 Years', '6 Years', 'Life-time'],
    correctIndex: 2,
    explanationHi: 'राज्यसभा एक स्थायी सदन है जो कभी भंग नहीं होता। इसके सदस्यों का कार्यकाल 6 वर्ष होता है और एक-तिहाई सदस्य हर 2 वर्ष में सेवानिवृत्त होते हैं।',
    explanationEn: 'Rajya Sabha is a permanent House not subject to dissolution; members serve 6-year terms with one-third retiring every 2 years.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 5
  },
  {
    id: 'q60',
    category: 'ECONOMY',
    difficulty: 'HARD',
    questionHi: 'भारत की "आकस्मिकता निधि" (Contingency Fund of India) किसके अधिकार और नियंत्रण में रखी जाती है?',
    questionEn: 'Under whose constitutional disposal and custody is the Contingency Fund of India placed?',
    optionsHi: ['वित्त मंत्री', 'भारत के राष्ट्रपति (President of India)', 'नियंत्रक एवं महालेखा परीक्षक (CAG)', 'संसद की प्राक्कलन समिति'],
    optionsEn: ['Finance Minister', 'President of India', 'Comptroller and Auditor General (CAG)', 'Estimates Committee'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 267 के तहत आकस्मिकता निधि राष्ट्रपति के नियंत्रण में होती है, जिससे अप्रत्याशित संकट के समय अग्रिम राशि जारी की जा सकती है।',
    explanationEn: 'Under Article 267, the Contingency Fund of India is at the disposal of the President to meet unforeseen expenditures.',
    rewardStat: 'finance',
    rewardAmount: 8
  },
  {
    id: 'q61',
    category: 'CONSTITUTION',
    difficulty: 'MEDIUM',
    questionHi: 'संविधान के किस अनुच्छेद के तहत राष्ट्रपति को मृत्युदंड क्षमा करने या सजा कम करने की शक्ति प्राप्त है?',
    questionEn: 'Under which Article does the President possess the power to grant pardons, reprieves, or remit punishment in death penalty cases?',
    optionsHi: ['अनुच्छेद 61', 'अनुच्छेद 72', 'अनुच्छेद 74', 'अनुच्छेद 76'],
    optionsEn: ['Article 61', 'Article 72', 'Article 74', 'Article 76'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 72 राष्ट्रपति को क्षमादान, दंड विराम, या सजा कम करने की संवैधानिक शक्ति प्रदान करता है।',
    explanationEn: 'Article 72 empowers the President of India to grant pardons, reprieves, respites or remissions of punishment.',
    rewardStat: 'leadership',
    rewardAmount: 7
  },
  {
    id: 'q62',
    category: 'ELECTIONS',
    difficulty: 'MEDIUM',
    questionHi: 'ग्राम पंचायत और नगर निगम के स्थानीय चुनाव कराने की संवैधानिक जिम्मेदारी किसकी होती है?',
    questionEn: 'Who is constitutionally responsible for conducting elections to Panchayats and Municipalities?',
    optionsHi: ['भारतीय निर्वाचन आयोग (ECI)', 'राज्य निर्वाचन आयोग (State Election Commission)', 'जिला कलेक्टर', 'राज्य का गृह विभाग'],
    optionsEn: ['Election Commission of India (ECI)', 'State Election Commission', 'District Collector', 'State Home Department'],
    correctIndex: 1,
    explanationHi: 'अनुच्छेद 243K और 243ZA के तहत स्थानीय निकायों के चुनाव कराने की जिम्मेदारी स्वतंत्र "राज्य निर्वाचन आयोग" की होती है, ECI की नहीं।',
    explanationEn: 'Under Articles 243K and 243ZA, local body elections are conducted by the respective State Election Commission.',
    rewardStat: 'administration',
    rewardAmount: 7
  },
  {
    id: 'q63',
    category: 'PARLIAMENT',
    difficulty: 'HARD',
    questionHi: 'संसदीय प्रक्रिया में बजट में कटौती के लिए प्रस्तुत "नीतिगत कटौती प्रस्ताव" (Policy Cut Motion) में राशि घटाकर कितनी करने की मांग की जाती है?',
    questionEn: 'In a Policy Cut Motion moved during budget grants debate, to what token amount is the demand reduced?',
    optionsHi: ['₹100', '₹1 (एक रुपया)', '₹1,000', 'मांग का 50%'],
    optionsEn: ['₹100', '₹1 (Re. 1)', '₹1,000', '50% of the demand'],
    correctIndex: 1,
    explanationHi: 'नीतिगत कटौती में अनुदान की मांग को घटाकर "₹1" करने का प्रस्ताव होता है, जो नीति की पूर्ण अस्वीकृति दर्शाता है। यदि यह पास हो जाए तो सरकार गिर सकती है।',
    explanationEn: 'A Policy Cut motion asks to reduce the demand to "Re. 1" to express disapproval of the policy underlying the demand.',
    rewardStat: 'strategy',
    rewardAmount: 9
  },
  {
    id: 'q64',
    category: 'DEMOCRACY',
    difficulty: 'EASY',
    questionHi: 'लोकतंत्र में नागरिकों द्वारा चुनी गई संसद व विधानसभाओं का मुख्य कार्य क्या है?',
    questionEn: 'In a representative democracy, what is the primary role of the Parliament and Legislative Assemblies?',
    optionsHi: [
      'केवल सरकारी भवनों का निर्माण करना',
      'कानून बनाना, सरकार से जवाबदेही सुनिश्चित करना और जनता का प्रतिनिधित्व करना',
      'अदालत में मुकदमों का फैसला करना',
      'विदेशी व्यापार पर पूर्ण रोक लगाना'
    ],
    optionsEn: [
      'Only constructing administrative buildings',
      'Enacting legislation, holding the executive accountable, and representing the citizens',
      'Deciding courtroom lawsuits',
      'Imposing complete bans on overseas commerce'
    ],
    correctIndex: 1,
    explanationHi: 'विधायिका का प्रमुख कार्य जनता की आवाज बनना, जनहित में कानून पारित करना और सरकार के कामकाज पर नियंत्रण रखना है।',
    explanationEn: 'The primary role of the legislature is lawmaking, scrutinizing government policy, and representing public interests.',
    rewardStat: 'leadership',
    rewardAmount: 6
  },
  {
    id: 'q65',
    category: 'CONSTITUTION',
    difficulty: 'EXPERT',
    questionHi: 'संविधान के 44वें संशोधन (1978) द्वारा किस अधिकार को मौलिक अधिकारों की सूची से हटाकर कानूनी अधिकार बनाया गया?',
    questionEn: 'Which right was removed from the list of Fundamental Rights and made a legal right by the 44th Amendment (1978)?',
    optionsHi: ['धार्मिक स्वतंत्रता का अधिकार', 'संपत्ति का अधिकार (Right to Property)', 'शोषण के विरुद्ध अधिकार', 'संवैधानिक उपचारों का अधिकार'],
    optionsEn: ['Right to Freedom of Religion', 'Right to Property', 'Right against Exploitation', 'Right to Constitutional Remedies'],
    correctIndex: 1,
    explanationHi: '44वें संशोधन द्वारा संपत्ति के अधिकार को अनुच्छेद 19(1)(f) और 31 से हटाकर अनुच्छेद 300A के तहत मात्र एक कानूनी अधिकार (Legal Right) बना दिया गया।',
    explanationEn: 'The 44th Amendment repealed Right to Property from Fundamental Rights and made it a constitutional legal right under Article 300A.',
    rewardStat: 'politicalKnowledge',
    rewardAmount: 10
  }
];
